# Generated by Django 5.0.6 on 2024-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='aguardando editora', max_length=50),
        ),
    ]
