# Generated by Django 5.0.6 on 2024-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_livro_editora3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='editora3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
